Added content
copperbits/awesome-libra pull request #1
Opened 2019-06-24 22:52 UTC by IrKor

Added FAQ, Resources, Current Problems, Useful links.

2019-06-25 13:27 UTC, skywinder requested changes
Let’s move faq to wiki. Just put a link to this section in the bottom

2019-06-25 21:09 UTC, IrKor commented
> Let’s move faq to wiki. Just put a link to this section in the bottom

Done

2019-06-26 10:06 UTC, skywinder commented on README.md
> +Regulators in countries where there are no clear rules for working with cryptocurrencies can stand on the way of launching Libra. In may 2019, the USA Senate Banking Committee wrote an open letter to
What about sources (links) to this statements?

2019-07-01 22:49 UTC, IrKor commented on README.md
> +Regulators in countries where there are no clear rules for working with cryptocurrencies can stand on the way of launching Libra. In may 2019, the USA Senate Banking Committee wrote an open letter to
Links to sources are in the FAQ (wiki), so I moved this section to the wiki.

2019-07-03 06:04 UTC, merged